### ISSUE TITLE
Error Finding the DB Name for scheduler-manager

### ISSUE THREAD

**Issue by Kartik-Rai** [IHTSDO/ihtsdo-ansible#27]
Hi there!,

Can somebody help me in finding out the db name we are going to use in schedule manager?
Any help will be appreciated, please refer the below link.

https://github.com/IHTSDO/ihtsdo-ansible/blob/3aad5acd656144e31d1da8b46711e23530bf6288/roles/IHTSDO.schedule-manager/templates/application.properties.j2#L17

Thanks & Regards 
Kartik Rai 
NRCES (India)

**Comment by pgwilliams** [comment]
Hi Kartik, it doesn't matter what you call it, as long as that database has been created as part of your installation process.  The schema itself will be populated the first time the schedule-manager runs.

In our install process, this file here is responsible for creating databases and database users:  https://github.com/IHTSDO/ihtsdo-ansible/blob/master/roles/IHTSDO.mysql/tasks/setup.yml

And then you'd have some host_vars defined somewhere (passed to ansible - if that's what you're using) that defines the users object:

mysql_users:
   - user:
       name: "{{ schedule_manager_db_username }}"
       password: "{{ schedule_manager_db_password }}"
       host: "%"
       privs: "{{ schedule_manager_dbname }}.*:ALL,GRANT"

but you could equally just create any database and fill that same name into your application.properties file.   My local one is called "dev_int_schedule_manager", but as long as whatever you call is is what appears in the application.properties file, it'll be fine.

**Comment by Kartik-Rai** [comment]
Hi Peter,
Actually i tried this method but you cleared my doubt that schema will be populated itself after schedule-manager runs. Thank you so much!

**Comment by pgwilliams** [comment]
Super!
